keys:
  - &master age1rundnwzcmw8wltfxdlrhelrkh5m8t80mej4jhfq6prr9k99uxg8qgqvjfw
  - &laptop_user age1dm5qhrgyaeyykqep0t7cyzdhmk8uqrj0u4kwlptpxa570w0l3drs80tscr
  - &laptop_host age1uh6p7659gdlnevxzryhe4mx39xkhr856q8v4ergzjcfl2atm2asq0ejrpx
  - &pi4_user age170a0x33mdeghu5mzse59yxdlk4tw3m829fptahxn0gau29kcgd6qr72dlv
  - &pi4_host age193l9m3xmzpn3zqe97fqjkv4dfxqth4d72rzf98ksuc5ctgeal3yst786rk
  - &grill age16sjq2pmrasnvu447v2qry399tqc45ua8jsc5zv8cwm7vq02lkspsurtu6g
  - &beau_grill age1k3fhza4mhr8a5dl3n508m88lcnyy4lnqrfwaz3svdzecq33hzqsq77p7dv
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *master
          - *laptop_user
          - *laptop_host
          - *pi4_user
          - *pi4_host
          - *grill
          - *beau_grill
