keys:
  - &master age1rundnwzcmw8wltfxdlrhelrkh5m8t80mej4jhfq6prr9k99uxg8qgqvjfw
  - &hosts:
    - &nix-laptop age1k4jxqxcwzl388cmq9s2te0dkddk7ua0gfldrj0p469kvcdmtqfhqng2z2f
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *master
        - *nix-laptop
