keys:
  - &master age1rundnwzcmw8wltfxdlrhelrkh5m8t80mej4jhfq6prr9k99uxg8qgqvjfw
  - &pi4_user age170a0x33mdeghu5mzse59yxdlk4tw3m829fptahxn0gau29kcgd6qr72dlv
  - &pi4_host age193l9m3xmzpn3zqe97fqjkv4dfxqth4d72rzf98ksuc5ctgeal3yst786rk
  - &grill age16sjq2pmrasnvu447v2qry399tqc45ua8jsc5zv8cwm7vq02lkspsurtu6g
  - &beau_grill age1k3fhza4mhr8a5dl3n508m88lcnyy4lnqrfwaz3svdzecq33hzqsq77p7dv
  - &laptop age1ta8989w025p3yzxdyan8827a0l05hagm6ac4g9dfnl6xwwmupacsxz3kd0
  - &beau_laptop age1rl4hv7d8j4wnpchqlswpvw9qtweq8ek2afcvaha6cyjr5fpv2f5s5wrk6s
  - &nas age1275f9lc7c8hykxtvgl3ttdeycffxg73fthwk7n57v3t654ddl30s8zze5w
  - &beau_nas age1cqnke5z3zcznun3g980llxvfde5zngkaqkhs4mky4wzwlvm6ng5ssnqnxw
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *master
          - *pi4_user
          - *pi4_host
          - *grill
          - *beau_grill
          - *laptop
          - *beau_laptop
          - *nas
          - *beau_nas
