keys:
  - &master age1rundnwzcmw8wltfxdlrhelrkh5m8t80mej4jhfq6prr9k99uxg8qgqvjfw
  - &bottom age1qa9kz72cuwkm0z2svvmp5e3fdp3da6ru4gwwgempw38e05fqe9zqfct3vv
  - &beau_bottom age1uvmu8j80cvq08znv54z4fk2hrv9rszcthfa625neq92uhyud5djsj2ayeq
  - &brick age1ntdsnyrcnwy700yny3syltatu0avep2jqn2c5z6e68vm9sntcppq6l0aan
  - &mikaerem_brick age1pz7m62pecza0kkw0y6nd9zmhvx6rgrwql6f3ejm3j963z63cwadqtnt4cf
  - &grill age16sjq2pmrasnvu447v2qry399tqc45ua8jsc5zv8cwm7vq02lkspsurtu6g
  - &beau_grill age1k3fhza4mhr8a5dl3n508m88lcnyy4lnqrfwaz3svdzecq33hzqsq77p7dv
  - &laptop age1ta8989w025p3yzxdyan8827a0l05hagm6ac4g9dfnl6xwwmupacsxz3kd0
  - &beau_laptop age1rl4hv7d8j4wnpchqlswpvw9qtweq8ek2afcvaha6cyjr5fpv2f5s5wrk6s
  - &nas age19v6f4dtenths5ykglat3lmfnfw2wy6yx33um7qyjwzmwk7ndr5lsdrc2a0
  - &beau_nas age1xx2x7epqxfq8rusvxswtnxx8czx4z94fzlw0jq59ncgnzds9e95suzfh45
  - &pi4 age193l9m3xmzpn3zqe97fqjkv4dfxqth4d72rzf98ksuc5ctgeal3yst786rk
  - &beau_pi4 age170a0x33mdeghu5mzse59yxdlk4tw3m829fptahxn0gau29kcgd6qr72dlv
  - &t480 age1xcfyee2ujfad8sq8u83rc23ht4akjthrhgx6tn4qef0uq9gh4pss2etw8v
  - &beau_t480 age10wvkj53rafjcgvvvtmlyx858h2h67jcph8wtp4yp38u00q46uplq2smw3f

creation_rules:
  - path_regex: secrets/bottom\.yaml$
    key_groups:
      - age:
          - *master
          - *nas
          - *beau_nas
          - *bottom
          - *beau_bottom
  - path_regex: secrets/brick\.yaml$
    key_groups:
      - age:
          - *master
          - *nas
          - *beau_nas
          - *brick
          - *mikaerem_brick
  - path_regex: secrets/grill\.yaml$
    key_groups:
      - age:
          - *master
          - *nas
          - *beau_nas
          - *grill
          - *beau_grill
  - path_regex: secrets/laptop\.yaml$
    key_groups:
      - age:
          - *master
          - *nas
          - *beau_nas
          - *laptop
          - *beau_laptop
  - path_regex: secrets/nas\.yaml$
    key_groups:
      - age:
          - *master
          - *nas
          - *beau_nas
  - path_regex: secrets/pi4\.yaml$
    key_groups:
      - age:
          - *master
          - *nas
          - *beau_nas
          - *pi4
          - *beau_pi4
  - path_regex: secrets/t480\.yaml$
    key_groups:
      - age:
          - *master
          - *nas
          - *beau_nas
          - *t480
          - *beau_t480
  - path_regex: secrets/minimal\.yaml$
    key_groups:
      - age:
          - *master
          - *nas
          - *beau_nas
          - *bottom
          - *beau_bottom
          - *brick
          - *mikaerem_brick
          - *grill
          - *beau_grill
          - *laptop
          - *beau_laptop
          - *pi4
          - *beau_pi4
          - *t480
          - *beau_t480
  - path_regex: secrets/common\.yaml$
    key_groups:
      - age:
          - *master
          - *nas
          - *beau_nas
          - *bottom
          - *beau_bottom
          - *brick
          - *mikaerem_brick
          - *grill
          - *beau_grill
          - *laptop
          - *beau_laptop
          - *pi4
          - *beau_pi4
          - *t480
          - *beau_t480
  - path_regex: secrets/network\.yaml$
    key_groups:
      - age:
          - *master
          - *nas
          - *beau_nas
          - *brick
          - *mikaerem_brick
          - *grill
          - *beau_grill
          - *laptop
          - *beau_laptop
          - *pi4
          - *beau_pi4
          - *t480
          - *beau_t480
  - path_regex: secrets/server\.yaml$
    key_groups:
      - age:
          - *master
          - *nas
          - *beau_nas
          - *brick
          - *mikaerem_brick
  - path_regex: secrets/client\.yaml$
    key_groups:
      - age:
          - *master
          - *nas
          - *beau_nas
          - *grill
          - *beau_grill
          - *pi4
          - *beau_pi4
          - *t480
          - *beau_t480
  - path_regex: secrets/main\.yaml$
    key_groups:
      - age:
          - *master
          - *nas
          - *beau_nas
          - *grill
          - *beau_grill
          - *laptop
          - *beau_laptop
          - *t480
          - *beau_t480
  - path_regex: secrets/work\.yaml$
    key_groups:
      - age:
          - *master
          - *nas
          - *beau_nas
          - *grill
          - *beau_grill
          - *laptop
          - *beau_laptop
          - *t480
          - *beau_t480
  - path_regex: secrets/gaming\.yaml$
    key_groups:
      - age:
          - *master
          - *nas
          - *beau_nas
          - *grill
          - *beau_grill
          - *t480
          - *beau_t480
