#!/usr/bin/env bash
set -euo pipefail

usage() {
	echo "Usage: generate-host-imports <host> [--repo <path>]" >&2
	exit 1
}

if [[ $# -lt 1 ]]; then
	usage
fi

host="$1"
shift

repo_root="$(pwd)"
while [[ $# -gt 0 ]]; do
	case "$1" in
	--repo)
		repo_root="$2"
		shift 2
		;;
	*)
		echo "Unknown argument: $1" >&2
		usage
		;;
	esac
done

if [[ ! -d $repo_root ]]; then
	echo "Repository path does not exist: $repo_root" >&2
	exit 1
fi

repo_root="$(cd "$repo_root" && pwd)"

out_dir="$repo_root/generated/imports"
out_file="$out_dir/$host.nix"

nix_expr="$(
	cat <<'NIX_EXPR'
  let
    flake = builtins.getFlake (toString ./.);
    lib = flake.inputs.nixpkgs.lib;
    custom = import ./lib {
      inherit lib;
      inputs = flake.inputs;
    };
    rootGraph = import ./inventory/explicit-imports/root-graph.nix;
    hostTargets = import ./inventory/explicit-imports/host-targets.nix;
    host = builtins.getEnv "TARGET_HOST";

    hostCfg =
      if builtins.hasAttr host hostTargets then
        builtins.getAttr host hostTargets
      else
        throw "Unknown host target: ${host}";

    resolveRoots =
      let
        visit = stack: name:
          let
            node =
              if builtins.hasAttr name rootGraph then
                builtins.getAttr name rootGraph
              else
                throw "Unknown root in graph: ${name}";
            parents = node.extends or [ ];
            hasCycle = builtins.elem name stack;
          in
          if hasCycle then
            throw "Cycle detected in root graph at: ${name}"
          else
            (builtins.concatMap (visit (stack ++ [ name ])) parents) ++ [ name ];
      in
      roots: lib.unique (builtins.concatMap (visit [ ]) roots);

    effectiveRoots = resolveRoots hostCfg.roots;
    importMap = custom.buildImportMap ./modules;

    sortPaths = paths: builtins.sort (a: b: a < b) (map toString paths);

    hostFiles =
      if (hostCfg.includeHostStem or false) then
        sortPaths (importMap.${host} or [ ])
      else
        [ ];

    rootFiles = builtins.concatMap (root: sortPaths (importMap.${root} or [ ])) effectiveRoots;
    selected = hostFiles ++ rootFiles;
  in
  {
    inherit host effectiveRoots selected;
  }
NIX_EXPR
)"

json_payload="$(
	cd "$repo_root"
	TARGET_HOST="$host" nix eval --json --impure --expr "$nix_expr"
)"

selected_count="$(jq '.selected | length' <<<"$json_payload")"
if [[ $selected_count -eq 0 ]]; then
	echo "No imports resolved for host '$host'. Refusing to write empty generated file." >&2
	exit 1
fi

mkdir -p "$out_dir"
tmp_file="$(mktemp)"

{
	echo "# Generated by generate-host-imports for host: $host"
	echo "# Effective roots: $(jq -r '.effectiveRoots | join(", ")' <<<"$json_payload")"
	echo "# Do not edit manually."
	echo "["

	jq -r '.selected[]' <<<"$json_payload" | while IFS= read -r abs_path; do
		if [[ $abs_path != "$repo_root/"* ]]; then
			echo "Resolved path is outside repo root: $abs_path" >&2
			exit 1
		fi

		rel_path="${abs_path#"$repo_root"/}"
		echo "  ../../$rel_path"
	done

	echo "]"
} >"$tmp_file"

mv "$tmp_file" "$out_file"

echo "Generated $out_file with $selected_count imports."
